### ISSUE TITLE
Simplify the instruction?

### ISSUE THREAD

**Issue by matbalez** [learn-co-curriculum/html-css-your-first-lab#2]
@pletcher  i worry the instruction to add line with div tag in the right place in the HTML file might be a little advanced for these very new users; they have presumably never seen HTML syntax before and this will all seem very foreign to them. what if the instruction instead was for them to replace some placeholder in the file with their name? i’m thinking something like:

 ```html
<!DOCTYPE html>
<html>
  <body>
    My name is HODOR and this is my first HTML page!
  </body>
</html>
```
and the instruction is to simply replace HODOR with your own name?

**Comment by pletcher** [comment]
Fixed with 8f99c5f
